#ifndef RZBUILDREPORT_H__
#define RZBUILDREPORT_H__

#include <RazerVM/InstructionSet.h>
#include <RazerVM/VirtualMachine.h>

#include <vector>

class aeReportLog
{
public:

	enum LogType
	{
		Debug,
		Warning,
		Error,
		Fatal
	};

	LogType m_type;
	int     m_severity;
	int     m_code;
	int     m_timeStamp;
	std::string m_tag;
	std::string m_message;

public:

	std::string buildString() const
	{
		return m_message;
	}
};

/**
	\class RzBuildReport
	\brief Accumulates errors and warnings generated by compilation
*/
class RzBuildReport
{
public:
	std::vector<aeReportLog> logs;
	bool                     m_enableStdOut;

public:

	RzBuildReport();

	void emitLog(const std::string& message);
	void emitCompilerError(const std::string& message);

	void addEntry(const aeReportLog& log);
};

#endif // RZBUILDREPORT_H__
